### ISSUE TITLE
Unable to run as Splunk user on system with restrictive umask

### ISSUE THREAD

**Issue by qubitrenegade** [chef-cookbooks/chef-splunk#106]
### Cookbook version
version '1.7.2'

### Chef-client version
12 and 13

### Platform Details
Tested on CentOS with umask 027

### Scenario:
Deploy Splunk as no root user.

### Steps to Reproduce:
Run server-cluster-master suite on OS with umask set to 027

### Expected Result:
Splunk should be able to start in a secure environment

### Actual Result:
Splunk is unable to start as the web.conf file is owned by root:root and has permissions of 640.  Thus the splunk user is unable to read the web.conf file and start the service.

**Comment by haidangwa** [comment]
@tas50 I think this should be closed, since #107 was merged a while ago. Also fixed in #119.
