### ISSUE TITLE
Slunk Service Restart Times Out

### ISSUE THREAD

**Issue by MarcusMaximus** [chef-cookbooks/chef-splunk#108]
### Cookbook version
chef-splunk (1.7.1)

### Chef-client version
Starting Chef Client, version 12.13.37

### Platform Details
ubuntu 16.04

### Scenario:
Provision  splunk server

### Steps to Reproduce:
My environment is pretty locked down. When I provision a splunk instance it gets as far as the service restart and fails since splunkd tries to the internet when starting the service but it can't so the operation times out. I can connect to the instance and restart the service manually and it will eventually restart but it takes about 5 mins. Is it possible to add an attribute to set a proxy server in the cookbook or a timeout period for the service restart section.

  * service[splunk] action start
================================================================================
                                       Error executing action `start` on resource 'service[splunk]'
                                       ================================================================================
                                       
                                       Mixlib::ShellOut::ShellCommandFailed
                                       ------------------------------------
                                       Expected process to exit with [0], but received '1'
                                       ---- Begin output of /bin/systemctl --system start splunk ----
                                       STDOUT: 
                                       STDERR: Job for splunk.service failed because a timeout was exceeded. See "systemctl status splunk.service" and "journalctl -xe" for details.
                                       ---- End output of /bin/systemctl --system start splunk ----
                                       Ran /bin/systemctl --system start splunk returned 1
                                       
                                       Resource Declaration:
                                       ---------------------
                                       # In /var/chef/cache/cookbooks/chef-splunk/recipes/service.rb
                                       
                                        88:   service 'splunk' do
                                        89:     supports status: true, restart: true
                                        90:     provider Chef::Provider::Service::Systemd
                                        91:     action [:enable, :start]
                                        92:   end
                                        93: else
 

### Expected Result:
Service expected to start 

### Actual Result:
starting the service fails

**Comment by haidangwa** [comment]
@MarcusMaximus

Can you try this with the latest version that was just released, 2.0.0? I think this was fixed with #119 merged, which seems similar to #121.

**Comment by haidangwa** [comment]
@tas50 I believe this has been resolved, as well.
