### ISSUE TITLE
Chef Splunk Config On Azure Marketplace Image Fails

### ISSUE THREAD

**Issue by samueljmello** [chef-cookbooks/chef-splunk#113]
### Cookbook version
1.7.3

### Chef-client version
13.0.118

### Platform Details
Ubuntu 14.04 - Splunk Azure Marketplace Image

### Scenario:
Configuration fails because it's can't read /opt/splunk/etc/splunk-launch.conf

### Steps to Reproduce:
Spin up a VM based off of the Slunk Azure marketplace image and run chef-client to configure Splunk

### Expected Result:
Chef should complete successfully and start

### Actual Result:
The process fails when attempting to start the Splunk service, stating:

`ERROR: Couldn't determine $SPLUNK_HOME or $SPLUNK_ETC; perhaps one should be set in environment`

This is because it cannot access `/opt/splunk/etc/splunk-launch.conf` as it is owned by root instead of splunk.

**Comment by haidangwa** [comment]
I believe this was fixed in v2.0.0 when #106 was fixed. Please verify and open a new issue if it hasn't been addressed.
