### ISSUE TITLE
initial_captain is not found anywhere in this cookbook except mentioned in a comment

### ISSUE THREAD

**Issue by mlcooper** [chef-cookbooks/chef-splunk#122]
### Cookbook version
2.0.0

### Chef-client version
14.x

### Platform Details
RHEL7

### Scenario:
[What you are trying to achieve and you can't?]

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

This line, https://github.com/chef-cookbooks/chef-splunk/blob/v2.0.0/recipes/setup_shclustering.rb#L69, mentions an attribute called `initial_captain`, but this attribute no longer exists in the cookbook.

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]
The comment above should be relevant to what is currently in the cookbook.
### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by haidangwa** [comment]
@tas50 This was resolved in #123.
