### ISSUE TITLE
splunk_app resource does not install the app

### ISSUE THREAD

**Issue by mlcooper** [chef-cookbooks/chef-splunk#140]
### Cookbook version
```
4.0.5
```

### Chef-client version
15.6.x

### Platform Details
RHEL8

### Scenario:
Use the `splunk_app` resource to install an app

### Steps to Reproduce:
Use a resource declaration such as this, with a template in the `templates` directory to install a splunk app:
```
splunk_app 'deploymentclient_base' do
  splunk_auth splunk_auth_info
  templates ['deploymentclient.conf.erb']
  action :enable
end
```

### Expected Result:
The app would get installed to `/opt/splunk/etc/apps`

### Actual Result:
The app doesn't get installed and therefore can't be enabled.
```
================================================================================
Recipe Compile Error in /home/cloud-user/cache/cookbooks/etech_splunk_installer/recipes/hec.rb
================================================================================

Chef::Exceptions::ValidationFailed
----------------------------------
Option action must be equal to one of: :nothing, :enable!  You passed :install.

Cookbook Trace:
---------------
  /home/cloud-user/cache/cookbooks/<redacted>/recipes/hec.rb:19:in `block in from_file'
  /home/cloud-user/cache/cookbooks/<redacted>/recipes/hec.rb:15:in `from_file'

Relevant File Content:
----------------------
/home/cloud-user/cache/cookbooks/<redacted>/recipes/hec.rb:

 12:
 13:  splunk_auth_info = data_bag_item('vault', "splunk_#{node.chef_environment}")['auth']
 14:
 15:  splunk_app 'deploymentclient_base' do
 16:    splunk_auth splunk_auth_info
 17:    templates ['deploymentclient.conf.erb']
 18:    # comment
 19>>   action [:install, :enable]
 20:  end
 21:
```
[This commit](https://github.com/chef-cookbooks/chef-splunk/commit/327ea3354bff96cb65b16b6c916cabb7e1669524#diff-2555fc5f2527c763e8d90c97ff35f29a) seems to have removed the `:install` action.  If you look in the [provider](https://github.com/chef-cookbooks/chef-splunk/blob/master/libraries/splunk_app_provider.rb) there is code for an install action but the commit makes it so you can't invoke it.

**Comment by haidangwa** [comment]
Fixed in v4.1.0 by https://github.com/chef-cookbooks/chef-splunk/pull/142
