### ISSUE TITLE
Support for deployment_server apps in the splunk_app resource

### ISSUE THREAD

**Issue by mlcooper** [chef-cookbooks/chef-splunk#141]
### Cookbook version
4.0.5

### Chef-client version
15.6.x

### Platform Details
RHEL8 - AWS

### Scenario:
The `splunk_app` resource does not currently permit you to deploy apps for the deployment server under `/opt/splunk/etc/deployment-apps`.  This is required for the Deployment Server.

### Steps to Reproduce:
Create a `splunk_app` resource to deploy an app and you will find there is no way to have the app deployed to anywhere other than `/opt/splunk/etc/apps`.

### Expected Result:
To be able to specify a location of where I want the app(s) deployed, other than the default location of `/opt/splunk/etc/apps`.  The `:disable` method will have to also support disabling an app that was deployed to a "custom" location.

### Actual Result:
You can't specify any location; they all get installed to `/opt/splunk/etc/apps` no matter what.

**Comment by haidangwa** [comment]
@mlcooper this is a new feature yet to be released, but it is under testing at the moment. The `app_dir` property is meant to be away to supply the absolute path where the app should be installed. It is documented in a branch README.md at the moment.

> node['splunk']['shclustering']['app_dir']: the path where search head clustering configuration will be installed (Default: /opt/splunk/etc/apps/0_autogen_shcluster_config)

Thanks for reporting the issue!
