### ISSUE TITLE
systemd unit file in cookbook has diverged from splunk documentation

### ISSUE THREAD

**Issue by mlcooper** [chef-cookbooks/chef-splunk#187]
In doing some work for number of open files on our splunk servers, I noticed that the systemd unit file in this cookbook has diverged from what splunk documents here, specifically in number **6**:

https://docs.splunk.com/Documentation/Splunk/8.0.6/Workloads/Configuresystemd

Additionally, it says [here](https://docs.splunk.com/Documentation/Splunk/8.0.6/Admin/RunSplunkassystemdservice#Upgrade_considerations_for_systemd) that if you upgraded from splunk 7.3.x that was configured to use systemd, that when you upgrade to 8.0.0 it removes a property (`User`) that is current in the systemd unit file in this cookbook.  The `User` property appears to be legacy since this cookbook is generally for splunk 8.x.x and higher.

**Comment by haidangwa** [comment]
@mlcooper The documentation link you provided doesn't pertain to Splunk Enterprise itself. It is documentation to setup Splunk's [Worload Management](https://docs.splunk.com/Documentation/Splunk/8.0.6/Workloads/Aboutworkloadmanagement) under systemd. I'm working on a change following this guide: https://docs.splunk.com/Documentation/Splunk/8.0.6/Admin/RunSplunkassystemdservice

**Comment by mlcooper** [comment]
Thanks for the clarification; I missed that it was for Workload Management.
