### ISSUE TITLE
inputs.conf is too restrictive

### ISSUE THREAD

**Issue by Sauraus** [chef-cookbooks/chef-splunk#36]
The inputs.conf file needs to be able to handle more than just tcp:// as a source, file monitoring for example must also be an option.

I therefore propose a breaking change that will change the inputs.conf template to no longer have the hard-coded tcp:// source and instead have a fully attribute driven input selector, something like this:

`default['splunk']['inputs_conf']['inputs'] = [
    {
        :inputname => 'monitor:///var/log/messages',
        :config => {
            :sourcetype => 'syslog',
            :disabled   => 'false',
            :followTail => '0'
      }
    },
    {
        :inputname => 'tcp://:123123',
        :config => {
            :sourcetype => 'syslog'
      }
    }
]`

NOTE: The above is only an illustration of options, very unlikely anyone would need both inputs in a inputs.conf file.

**Comment by bruce-davis** [comment]
data_bags/splunk_inputs/default.json
{
	"id": "default",
	"stanzas": {
		"[monitor:///var/ossec/log]": {
			"followTail": "1"
		},
		"[monitor://$SPLUNK_HOME/var/log/splunk]": {
			"_TCP_ROUTING": "*",
			"blacklist": "metrics\\.log",
			"followTail": "1",
			"index": "_internal"
		},
		"[monitor:///proc/vmmemctl]": {
		}
	}
}

splunk/recipes/forwarder.rb

# Load default Splunk_inputs data bag items
host_inputs = []
begin
  host_input_items = data_bag_item('splunk_inputs', 'default')
  host_input_items ["stanzas"].each do |stanza|
    host_inputs.push stanza
  end
end

template "#{node['splunk']['home']}/etc/system/local/inputs.conf" do
  source "forwarder/inputs.conf.erb"
  owner "splunk"
  group "splunk"
  mode "0644"
  variables(
    :host_inputs => host_inputs
  )
  notifies :restart, resources(:service => "splunk")
end

splunk/templates/default/forwarder/inputs.conf.erb 
# forwarder inputs.conf
[default]
host = <%= node['fqdn'] %>
index = <%= @index %>

<% @host_inputs.sort.uniq.each do | stanza_name, stanza_details | -%>
<%= stanza_name %>
<% stanza_details.sort.each do | stanza_detail_name, stanza_detail_value | -%>
<%= stanza_detail_name %>=<%= stanza_detail_value %>
<% end -%>
<% end -%>


Results in:
# forwarder inputs.conf
[default]
host = chef-app01.opsdev.bos.setg
index = ops

[monitor://$SPLUNK_HOME/var/log/splunk]
_TCP_ROUTING=*
blacklist=metrics\.log
followTail=1
index=_internal

[monitor:///proc/vmmemctl]

[monitor:///var/ossec/log]
followTail=1

**Comment by jblaine** [comment]
I could swear I +1'd this before, but clearly didn't. I agree completely with @Sauraus

**Comment by danieljimenez** [comment]
+1

**Comment by monokal** [comment]
+1

**Comment by haidangwa** [comment]
Looks like this was addressed in #105. If you think there are additional features missing, please open a new issue.
