### ISSUE TITLE
Option to install splunkforwarder via system pkg manager (ie yum repo) not download URL

### ISSUE THREAD

**Issue by chico-san** [chef-cookbooks/chef-splunk#50]
I have a use case where splunkforwarder RPM is already installed via company wide managed yum repo, such that the installed version is newer than what it is set in attributes.

It'd be nice if cookbook had option for a "no frills" package install which just relies on the system pkg manager instead of installing from cached remote file from the hardcoded URL in attributes

**Comment by haidangwa** [comment]
This could be relatively simple to add to the [splunk_installer](https://github.com/chef-cookbooks/chef-splunk/blob/master/resources/splunk_installer.rb) resource that was added in v2.0.0.
