### ISSUE TITLE
node['splunk']['tcpout_server_config_map'] doesn't exist

### ISSUE THREAD

**Issue by ryanl-ee** [chef-cookbooks/chef-splunk#56]
Hi all, just an FYI and probably more of an issue with the readme, but it describes an attribute "node['splunk']['tcpout_server_config_map']" used to set up SSL. That attribute isn't referenced anywhere in the cookbook. I was able to just add the relevant attributes "sslCertPath", etc. to my "override['splunk']['outputs_conf']" attribute array. I'm guessing it was removed without updating the readme. Thanks for reading!

**Comment by iennae** [comment]
Thanks for pointing out the documentation issue. This has been resolved with Issue #88.
