### ISSUE TITLE
node['platform_family'] is now required and should be specified as such in the installer definition

### ISSUE THREAD

**Issue by fallwith** [chef-cookbooks/chef-splunk#61]
After upgrading from v1.3 to v1.4, all of the specs for one of our projects started failing. It turns out that the project was not setting `node['platform_family']`, and this caused `splunk_installer.rb`'s `declare_resource` block to receive a `nil` for `local_package_resource` unexpectedly.

I think the `case` statement from line 54 should have an `else` with a `fail` if `node['platform_family']` is `nil`, but I'm not sure if it was your intention to make it required or not.

```ruby
# cookbooks/chef-splunk/definitions/splunk_installer.rb:

 53:
 54:    local_package_resource = case node['platform_family']
 55:                             when 'rhel'   then :rpm_package
 56:                             when 'debian' then :dpkg_package
 57:                             when 'omnios' then :solaris_package
 58:                             end
 59:
 60:   declare_resource local_package_resource, params[:name] do
 61:      source cached_package.gsub(/\.Z/, '')
 62:      options pkgopts.join(' ') if platform?('omnios')
 63:    end
 64:  end
 65:
```

**Comment by tas50** [comment]
node['platform_family'] is present in Chef 11.X which is stated as a requirement in the readme.  I believe it was added in one of the later Chef 10 releases.  We no longer support Chef 10 and you'll need to upgrade to a more recent Chef release to use this cookbook.

**Comment by fallwith** [comment]
We use Chef 12. The issue was experienced with spec testing (using ChefSpec). My original suggestion stands; the `case` statement could really benefit from an `else` clause that handles a situation where `node['platform_family']` is either unset or set to a value that is not one of the three expected values.
