### ISSUE TITLE
undefined method `provides' (breaks Chef 11 support)

### ISSUE THREAD

**Issue by nothsa** [chef-cookbooks/chef-splunk#63]
With Chef 11 I get this "undefined method" error when running this cookbook, which is similar to this chef-vault issue: https://github.com/chef-cookbooks/chef-vault/issues/36

This is caused by the change in this commit: https://github.com/chef-cookbooks/chef-splunk/commit/f06b03bab59c8b01527d06e61363d420dae788e4

This essentially breaks support on Chef 11. Could you please either update the "Requirements" section in the README.md file to reflect that Chef 11 is no longer supported, or update the "libraries/splunk_app_provider.rb" file to support Chef 11 installations?

Thanks =)

**Comment by sworisbreathing** [comment]
My bad. I'll open a PR to fix it shortly.
