### ISSUE TITLE
Adding monitors and indexes via resources

### ISSUE THREAD

**Issue by genslein** [chef-cookbooks/chef-splunk#64]
Hey all,

I was looking through the source here and I can't see a generic way to add indexes and monitors via the standard Chefified resources. Does this exist in the cookbook today? If so where? Currently we just have shell resources executing the commands by hand but would rather have a more inline, idempotent way of doing this.

**Comment by sworisbreathing** [comment]
I think there's a broader discussion to be had about how to properly manage splunk configs. There are several different ways of doing it (e.g. templating the entire config file, using `file_edit`, or rolling out a splunk app), and each have their pros and cons.

I tend to favor app bundles for managing .conf files in my own deployments (which I can manage with the `splunk_app` resource), but I understand that's not the ideal approach for a lot of other folks.

**Comment by jblaine** [comment]
+1 doesn't exist, would be great if it existed. Previous PR to add this was https://github.com/chef-cookbooks/chef-splunk/pull/8  ... and closed due to not having tests :(
