### ISSUE TITLE
Download fails (404)

### ISSUE THREAD

**Issue by pulkkla-nc** [chef-cookbooks/chef-splunk#73]
Seems that Splunk might have changed the download procedure so that the installation package download requires registration & sign-in which prevents the use of default download url for this cookbook. Result for downloading any of the packages is "404 not found".

**Comment by akemner** [comment]
happening to me as well

**Comment by iiro** [comment]
Happening here as well.

**Comment by akemner** [comment]
looks like the url might have changed.

**Comment by rarsan** [comment]
This has been fixed in https://github.com/rarsan/chef-splunk.
PR #74 submitted to fix this upstream.

**Comment by akemner** [comment]
i opened a ticket with splunk support for the issue and asked for a repository so it can be mirrored. i'd recommend everyone thats having this problem do the same.

**Comment by dallinwright** [comment]
You can set the attribute manually in your wrapper cookbook or role file to overwrite and use the correct URL. All you need to do it set this value:

default['splunk']['forwarder']['url'] = 'http://download.splunk.com/products/universalforwarder/releases/6.2.1/linux/splunkforwarder-6.2.1-245427-linux-2.6-x86_64.rpm'
