### ISSUE TITLE
Nothing happening when using latest version with Splunk 6.5.1 paths

### ISSUE THREAD

**Issue by sommestad** [chef-cookbooks/chef-splunk#85]
### Cookbook version
https://github.com/chef-cookbooks/chef-splunk/commit/739855e15987de2bb33b91aa6aa82ecdfd155d83

### Chef-client version
Chef: 12.14.89

### Platform Details
Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-71-generic x86_64)

### Scenario:
Install the latest (6.5.1) version of Splunk on a machine having 6.3.3 installed (also with chef-splunk cookbook).

### Steps to Reproduce:
1. Install latest version of this cookbook
2. Run `chef-client` on the machine  in question

### Expected Result:
Splunk 6.5.1 to be installed.

### Actual Result:
- It doesn't install 6.5.1. However, it does download the .deb file, but doesn't seem to proceed with the actual installation. 
- Have tried booting the machine.
- Re-running chef-client many times (also tried removing the .deb file to try trigger an install).

**From chef client log**
```
Recipe: chef-splunk::install_server
  * remote_file[/var/chef/cache/splunk-6.5.1-f74036626f0c-linux-2.6-amd64.deb] action create_if_missing
    - create new file /var/chef/cache/splunk-6.5.1-f74036626f0c-linux-2.6-amd64.deb
    - update content in file /var/chef/cache/splunk-6.5.1-f74036626f0c-linux-2.6-amd64.deb from none to 34bf4d
    (file sizes exceed 10000000 bytes, diff output suppressed)
  * dpkg_package[splunk] action install (up to date)
Recipe: chef-splunk::service
  * directory[/opt/splunk] action create (up to date)
  * directory[/opt/splunk/var] action create (up to date)
  * directory[/opt/splunk/var/log] action create (up to date)
  * directory[/opt/splunk/var/log/splunk] action create (up to date)
  * execute[/opt/splunk/bin/splunk enable boot-start --accept-license --answer-yes] action run (skipped due to only_if)
  * ruby_block[splunk_fix_file_ownership] action run (skipped due to not_if)
  * template[/etc/init.d/splunk] action create (up to date)
  * service[splunk] action start (up to date)
```

**Still 6.3.3 installed.**
```
~$ dpkg --status splunk
Package: splunk
Status: install ok installed
Maintainer: Splunk Inc. <info@splunk.com>
Architecture: amd64
Version: 6.3.3
Description: Splunk The platform for machine data.
```

**Downloaded file seems to be 6.5.1**
```
~$ dpkg-deb -f /var/chef/cache/splunk-6.5.1-f74036626f0c-linux-2.6-amd64.deb
Package: splunk
Version: 6.5.1
Maintainer: Splunk Inc. <info@splunk.com>
Architecture: amd64
Description: Splunk The platform for machine data.
```

**Comment by sommestad** [comment]
Anyone? Would _really_ like to move to version 6.5, but this is hindering that...

**Comment by rarsan** [comment]
This is determined by the the underlying resource [dpkg_package](https://docs.chef.io/resources.html#dpkg-package) used by [splunk_installer](https://github.com/chef-cookbooks/chef-splunk/blob/master/definitions/splunk_installer.rb).

I think the default behavior of `dpkg --install` is to upgrade a package if it's already installed, but you may need to specify an explicit `version` property or `options` to be passed for that commend. Look for that resource declaration at the end of `splunk_installer` definition.

**Comment by cheeseplus** [comment]
Are you actually running the with `node['splunk']['upgrade_enabled']` as mentioned in the readme? If so it should include the upgrade recipe.

**Comment by sommestad** [comment]
@cheeseplus That's a good point. Is it supposed to be set?

I read the docs as if it was only relevant pre 6.0.1:

> This recipe can be used to upgrade a splunk installation, for example from an existing 4.2.1 to 4.3.7. The default recipe can be used for 6.0.1 after upgrading earlier versions is completed.

Also, I didn't find any traces of us ever setting that property before, but maybe we've done upgrades some other way (e.g. always on clean machines).

**Comment by sommestad** [comment]
Could it be an issue that the server URL is pointing to 6.3.3 (https://github.com/chef-cookbooks/chef-splunk/blob/master/attributes/default.rb#L88), or is that just something unrelated?

**Comment by sommestad** [comment]
So, I tried setting `node.override['splunk']['upgrade_enabled'] = true` and specifying the paths to the correct .deb version, but it still does nothing... 😒 

```
Recipe: chef-splunk::install_server
  * remote_file[/var/chef/cache/splunk-6.5.1-f74036626f0c-linux-2.6-amd64.deb] action create_if_missing
    - create new file /var/chef/cache/splunk-6.5.1-f74036626f0c-linux-2.6-amd64.deb
    - update content in file /var/chef/cache/splunk-6.5.1-f74036626f0c-linux-2.6-amd64.deb from none to 34bf4d
    (file sizes exceed 10000000 bytes, diff output suppressed)
  * dpkg_package[splunk] action install (up to date)
```

**Comment by rarsan** [comment]
@sommestad I was able to repro the issue. It appears Chef [dpkg](https://github.com/chef/chef/blob/9600b1c8d3e5242a57757d83342a59692dbfaa21/lib/chef/provider/package/dpkg.rb) resource implementation skips installation simply on package found. I have a workaround in flight to explicitly set version.
Also, to successfully upgrade, you need to do all of the following:
- set upgrade url `node['splunk']['upgrade']['server_url']`
- set flag `node['splunk']['upgrade_enabled']`
- add upgrade recipe to run list: `recipe[chef-splunk::upgrade]`

**Comment by rarsan** [comment]
#91 merged. closing.

**Comment by sommestad** [comment]
Worked perfectly fine! Thanks!
