### ISSUE TITLE
Bump rev so supermarket will see updates

### ISSUE THREAD

**Issue by cringdahl** [chef-cookbooks/chef-splunk#95]
Please bump the rev to 1.6.x or 1.7.x. There are changes such as 'server_list' that would be very useful, but only exist in master.

**Comment by iennae** [comment]
@rarsan has added a bunch of new things to this cookbook which is great. He may not be ready for a release to be made. If a release is ready @rarsan, I can help with that. Thanks!

**Comment by rarsan** [comment]
This is ready for release.
Here are the list of fixes & enhancements:

-          Fix CI and Kitchen Dokken

-          Fix upgrade recipe

-          Fix install on SUSE platform

-          Add Splunk 6.6 URLs as default

-          Support static list of indexers for client recipe

-          Support multisite indexer clustering

-          Support search head clustering


I'm currently on vacation and can take care of it upon my return first week
of July. Otherwsie, Jennifer feel free to push a release if this is needed
more urgently.
Thanks.

**Comment by iennae** [comment]
Thanks so much @rarsan! You totally rock. Will release shortly.

**Comment by iennae** [comment]
This has been released as v1.7.0.
