### ISSUE TITLE
Version 1.6.0 in supermarket is not the same that version 1.6.0 in github

### ISSUE THREAD

**Issue by ludusregio** [chef-cookbooks/chef-splunk#97]
When I download the supermarket version of chef-splunk 1.6.0 the recipe client.rb does not contain the proper code to handle the attribute node['splunk']['server_list'] if the splunk server is set statically instead of searching.
However, when I download the github version 1.6.0, the client.rb contains the proper entry to assign the content of node['splunk']['server_list'] to the variable server_list:
```

# fallback to statically defined server list as alternative to search
server_list = node['splunk']['server_list'] if server_list.empty?
```
This piece of code is missing from the same version in supermarket.

Please, you could check and synchronize supermarket with the correction?

**Comment by iennae** [comment]
Hi,

The version on github hadn't been released yet. I've released it now as v1.7.0.
