### ISSUE TITLE
systemd service permissions

### ISSUE THREAD

**Issue by ludusregio** [chef-cookbooks/chef-splunk#98]
My logs are full of following messages:

> Jun 28 14:51:59 servername systemd: Configuration file /etc/systemd/system/splunk.service is marked executable. Please remove executable permission bits. Proceeding anyway.
> Jun 28 14:51:59 servername systemd: Configuration file /etc/systemd/system/splunk.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.

This is due to the file /etc/systemd/system/splunk.service having the execute bit set for the owner and not read to world. Can this be corrected in the following code? Instead of mode 700, mode 644?

```
 template '/etc/systemd/system/splunk.service' do
    source 'splunk-systemd.erb'
    mode '700'
    variables(
      splunkdir: splunk_dir,
      runasroot: node['splunk']['server']['runasroot']
    )
  end
```

**Comment by tas50** [comment]
I’m adding the Type: Jump In GitHub label to this issue. This is a great issue for someone to get their feet wet with and we’d love a PR to resolves the issue.

**Comment by tas50** [comment]
Fixed and soon to be released
